title: Dino jump
hero_image: images/banner.png
description: Make a jumping game in this Code Club arcade project.
listed: false
pdf: false
landing: true
steps:
  - title: Add a character
  - title: Choose a backdrop
  - title: Set the starting position
  - title: Jump into the air
  - title: Land the jump
    completion:
      - engaged
  - title: Add an obstacle
  - title: Create clones
  - title: Move each clone
  - title: Remove old clones
  - title: Randomise the gaps
  - title: Animate the clones
  - title: Stop after a collision
  - title: Add a collision sound
  - title: Add a score
  - title: Score each successful jump
    completion:
      - internal
  - title: Challenge
    completion:
      - external
    challenge: true
