title: Dino jump
hero_image: images/banner.png
description: Make a jumping game in this Code Club arcade project.
listed: true
pdf: false
steps:
  - title: Add a character
  - title: Choose a backdrop
    completion:
      - engaged
  - title: Set the starting position
  - title: Set the character's starting look
  - title: Jump into the air
  - title: Land the jump
  - title: Add an obstacle
  - title: Size and position the obstacle
  - title: Make the obstacle face left
  - title: Hide the original obstacle
  - title: Create obstacle clones
  - title: Show each obstacle
  - title: Randomise the gaps
  - title: Set the obstacle speed
  - title: Move the obstacles
  - title: Remove old obstacles
  - title: Animate the obstacles
  - title: Detect a collision
  - title: Stop after a collision
  - title: Add a collision sound
  - title: Make the score variable
  - title: Reset the score
  - title: Score avoided obstacles
  - title: Test the whole game
  - title: Tune the obstacle speed
  - title: Tune the gaps
  - title: Tune the obstacle height
    completion:
      - internal
  - title: Make it your own
    challenge: true
    completion:
      - external
